FROM ruby:3.4.8

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

RUN apt-get update -qq \
  && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    vim \
    ca-certificates \
  && npm install -g corepack \
  && corepack enable \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /myapp

RUN gem install bundler

COPY . /myapp